sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/project-euler .
script:
  - docker run -it --rm jeremymiller/project-euler stack test --no-terminal --skip-ghc-check --coverage
after_success:
  - docker run -it --rm jeremymiller/project-euler ./shc project-euler solutions-test
