language: sh  # don't use "language: haskell" since we're using stack to install GHC
dist: trusty
cache:
  directories:		
    - $HOME/.stack/
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack setup --no-terminal --skip-ghc-check
  - stack build --no-terminal --skip-ghc-check --coverage  # --coverage used to make sure code coverage is generated, see https://github.com/commercialhaskell/stack/issues/1305
script:
  - docker run -it --rm jeremymiller/project-euler hlint .
  - travis_wait stack test --no-terminal --skip-ghc-check --coverage
after_success:
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj -C ~/.local/bin
  - chmod +x ~/.local/bin/shc
  - ~/.local/bin/shc project-euler doctest  # doesn't work inside docker
  - ~/.local/bin/shc project-euler solutions-test  # doesn't work inside docker
