# don't use "language: haskell" since we're using stack to install GHC
language: sh
dist: xenial
group: edge
cache:
  directories:
    - $HOME/.stack/
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check build
script:
  - stack --no-terminal --skip-ghc-check test
